# Package Overview
package_name: Classification_model

# Data Files
training_data_file: train.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (sale price)
target: survived

pipeline_name: Classification_model
pipeline_save_file: Classification_model_output_v


features:
  - pclass
  - name
  - sex
  - age
  - sibsp
  - parch
  - ticket
  - fare
  - cabin
  - embarked
  - boat
  - body
  - home.dest

# set train/test split
test_size: 0.1

# to set the random seed
random_state: 0

alpha: 0.001

# categorical variables with NA in train set
NUMERICAL_VARIABLES:
  - age
  - fare

CATEGORICAL_VARIABLES:
  - sex
  - cabin
  - embarked
  - title

CABIN:
  - CABIN